<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a7c7efe3-264f-48e0-8884-6f3db542014a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevNoteAI.Application\DevNoteAI.Application.csproj" />
    <ProjectReference Include="..\DevNoteAI.Infrastructure\DevNoteAI.Infrastructure.csproj" />
  </ItemGroup>

</Project>
